name: Labels
on:
  - pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: verify
        uses: yogevbd/enforce-label-action@2.1.0
        with:
          REQUIRED_LABELS_ANY: "major,minor,patch,ci"
